
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.draw.DottedLineSeparator;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import static java.lang.Math.pow;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.StyleConstants.FontConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jash
*/






public class New extends javax.swing.JFrame {
    
    public static String name="",email="",phone="",linkid="";
    String schoolname="",schoolpercent="",jc="",jcpercent="";
    String collegename="",collegedeg="",collegecgpa="",degname,descript;
    String lang,skills,achieve,achieve_descript;
    String image;
    ArrayList<New_Project> project=new ArrayList<New_Project>();
    ArrayList<Experience> exp=new ArrayList<Experience>();
    String projectname,projdescript;
    int i=0;
    boolean image_checker=false;
    public New() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        degreename = new javax.swing.ButtonGroup();
        jTextField3 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        j_name = new javax.swing.JLabel();
        j_nametext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        j_linkedtext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        j_emailtext = new javax.swing.JTextField();
        jl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        phoneno = new javax.swing.JTextField();
        jl1 = new javax.swing.JLabel();
        jl2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        imagepath = new javax.swing.JTextField();
        imageSay = new javax.swing.JLabel();
        checkImagebtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        j_schooltext = new javax.swing.JTextField();
        j_schoolpertext = new javax.swing.JTextField();
        j_jctext = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        j_jcpertext = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cgpa = new javax.swing.JTextField();
        clgname = new javax.swing.JTextField();
        clgdeg = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jl3 = new javax.swing.JLabel();
        jl4 = new javax.swing.JLabel();
        jl5 = new javax.swing.JLabel();
        jl6 = new javax.swing.JLabel();
        jl7 = new javax.swing.JLabel();
        jl8 = new javax.swing.JLabel();
        jl9 = new javax.swing.JLabel();
        deg_diploma = new javax.swing.JRadioButton();
        deg_hsc = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        language = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        skillset = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        achievement = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        achievement_description = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        proname = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prodesname = new javax.swing.JTextArea();
        newprojectBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        companyname = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        workdone = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        workdescript = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        j_submit = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        j_name.setText("Full Name:");

        j_nametext.setText("Enter your name");
        j_nametext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                j_nametextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                j_nametextFocusLost(evt);
            }
        });
        j_nametext.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                j_nametextInputMethodTextChanged(evt);
            }
        });
        j_nametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_nametextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("LinkedIn ID:");

        j_linkedtext.setText("Enter your LinkedIn iD");
        j_linkedtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                j_linkedtextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                j_linkedtextFocusLost(evt);
            }
        });
        j_linkedtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_linkedtextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Email ID:");

        j_emailtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_emailtextActionPerformed(evt);
            }
        });

        jl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl.setForeground(new java.awt.Color(255, 51, 51));
        jl.setText("*");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Phone No.:");

        phoneno.setText("Enter your  phone number");
        phoneno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phonenoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phonenoFocusLost(evt);
            }
        });
        phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenoActionPerformed(evt);
            }
        });

        jl1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl1.setForeground(new java.awt.Color(255, 51, 51));
        jl1.setText("*");

        jl2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl2.setForeground(new java.awt.Color(255, 51, 51));
        jl2.setText("*");

        jLabel26.setText("( @gmail.com if you do not add)");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Image Path:");

        imagepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagepathActionPerformed(evt);
            }
        });

        imageSay.setText(".");

        checkImagebtn.setText("Browse Image");
        checkImagebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkImagebtnActionPerformed(evt);
            }
        });

        jButton2.setText("Check Image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(j_name, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel30))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(phoneno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j_linkedtext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j_nametext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(j_emailtext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(imagepath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl)
                                    .addComponent(jl1)
                                    .addComponent(jl2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(checkImagebtn))))
                    .addComponent(imageSay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_nametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(j_emailtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl2))
                .addGap(2, 2, 2)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(j_linkedtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(imagepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkImagebtn)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageSay)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personal Info", jPanel1);

        jLabel3.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        jLabel3.setText("School");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Name:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Percentage:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Percentage:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Name:");

        j_schooltext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_schooltextActionPerformed(evt);
            }
        });

        j_schoolpertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_schoolpertextActionPerformed(evt);
            }
        });

        j_jctext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_jctextActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        jLabel8.setText("Junior College");

        j_jcpertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_jcpertextActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 2, 18)); // NOI18N
        jLabel12.setText("University");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Name:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Degree:");

        cgpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgpaActionPerformed(evt);
            }
        });

        clgname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clgnameActionPerformed(evt);
            }
        });

        clgdeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clgdegActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("CGPA:");

        jl3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl3.setForeground(new java.awt.Color(255, 51, 51));
        jl3.setText("*");

        jl4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl4.setForeground(new java.awt.Color(255, 51, 51));
        jl4.setText("*");

        jl5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl5.setForeground(new java.awt.Color(255, 51, 51));
        jl5.setText("*");

        jl6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl6.setForeground(new java.awt.Color(255, 51, 51));
        jl6.setText("*");

        jl7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl7.setForeground(new java.awt.Color(255, 51, 51));
        jl7.setText("*");

        jl8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl8.setForeground(new java.awt.Color(255, 51, 51));
        jl8.setText("*");

        jl9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl9.setForeground(new java.awt.Color(255, 51, 51));
        jl9.setText("*");

        degreename.add(deg_diploma);
        deg_diploma.setText("Diploma");
        deg_diploma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deg_diplomaActionPerformed(evt);
            }
        });

        degreename.add(deg_hsc);
        deg_hsc.setText("HSC/CBSE");
        deg_hsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deg_hscActionPerformed(evt);
            }
        });

        jLabel31.setText("( in %)");

        jLabel32.setText("(in %)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j_schooltext)
                                    .addComponent(j_schoolpertext)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(43, 43, 43)
                                .addComponent(j_jcpertext))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(j_jctext, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cgpa, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                    .addComponent(clgdeg, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(clgname, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(deg_diploma, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deg_hsc, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl3)
                    .addComponent(jl5)
                    .addComponent(jl7)
                    .addComponent(jl8)
                    .addComponent(jl9)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jl6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(j_schooltext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jl3))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl4)
                            .addComponent(jLabel31))
                        .addGap(13, 13, 13)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(j_schoolpertext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j_jctext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl5))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(j_jcpertext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jl6))))
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deg_diploma)
                            .addComponent(deg_hsc))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clgname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl8)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clgdeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl9)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cgpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jl7))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Education", jPanel2);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Languages:");

        language.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("SkillSet:");

        skillset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skillsetActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Achievement Name:");

        achievement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                achievementActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Achievement Description:");

        achievement_description.setColumns(20);
        achievement_description.setRows(5);
        jScrollPane2.setViewportView(achievement_description);

        jLabel25.setText("Please keep the description as short as possible(<50 chars)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel18)
                            .addComponent(jLabel11)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(language, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(skillset, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(achievement)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(skillset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(achievement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(36, 36, 36)))
                .addComponent(jLabel25)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Skills & Achievements", jPanel3);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Project Name:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Project Description:");

        prodesname.setColumns(20);
        prodesname.setRows(5);
        prodesname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                prodesnameInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(prodesname);

        newprojectBtn.setText("Add This Project");
        newprojectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newprojectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(proname)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(newprojectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(proname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(newprojectBtn)
                .addGap(59, 59, 59))
        );

        jTabbedPane1.addTab("Projects", jPanel4);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Company Name:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Designation:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Work Description:");

        workdescript.setColumns(20);
        workdescript.setRows(5);
        jScrollPane3.setViewportView(workdescript);

        jButton1.setText("Add this Experience");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(workdone)
                            .addComponent(companyname)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jButton1)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(companyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(workdone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel29))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Experience", jPanel5);

        jLabel20.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel20.setText("MAKE SURE YOU HAVE FILLED ");

        jLabel19.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel19.setText("ALL COMPULSORY FIELDS");

        j_submit.setText("SUBMIT");
        j_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_submitActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Thank You!");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel22.setText("Brought to you by Manav,Madhur and Jash");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(j_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel20)
                .addGap(28, 28, 28)
                .addComponent(jLabel19)
                .addGap(55, 55, 55)
                .addComponent(j_submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Generate CV", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void j_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_submitActionPerformed
        if(check_submit())
        submit_cv();
        // TODO add your handling code here:
    }//GEN-LAST:event_j_submitActionPerformed

    private void newprojectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newprojectBtnActionPerformed
        try{
            projectname=proname.getText();
            projdescript=prodesname.getText();
            New_Project obj=new New_Project(projectname,projdescript);
            project.add(obj);
            //System.out.println(projectname[i]+projdescript[i]);
            proname.setText("");
            prodesname.setText("");
        }
        catch(Exception e){}
    }//GEN-LAST:event_newprojectBtnActionPerformed

    private void prodesnameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_prodesnameInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_prodesnameInputMethodTextChanged

    private void clgdegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clgdegActionPerformed

        collegedeg=clgdeg.getText();
    }//GEN-LAST:event_clgdegActionPerformed

    private void clgnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clgnameActionPerformed
        // TODO add your handling code here:
        collegename=clgname.getText();
    }//GEN-LAST:event_clgnameActionPerformed

    private void cgpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgpaActionPerformed
        // TODO add your handling code here:
        collegecgpa=cgpa.getText();
    }//GEN-LAST:event_cgpaActionPerformed

    private void j_jcpertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_jcpertextActionPerformed
        // TODO add your handling code here:
        jcpercent=j_jcpertext.getText();
    }//GEN-LAST:event_j_jcpertextActionPerformed

    private void j_jctextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_jctextActionPerformed
        jc=j_jctext.getText();// TODO add your handling code here:
    }//GEN-LAST:event_j_jctextActionPerformed

    private void j_schoolpertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_schoolpertextActionPerformed
        schoolpercent=j_schoolpertext.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_j_schoolpertextActionPerformed

    private void j_schooltextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_schooltextActionPerformed
        schoolname=j_schooltext.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_j_schooltextActionPerformed

    private void phonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenoActionPerformed
        phone=phoneno.getText();// TODO add your handling code here:
    }//GEN-LAST:event_phonenoActionPerformed

    private void j_emailtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_emailtextActionPerformed
        email=j_emailtext.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_j_emailtextActionPerformed

    private void j_linkedtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_linkedtextActionPerformed
        linkid=j_linkedtext.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_j_linkedtextActionPerformed

    private void j_nametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_nametextActionPerformed
        name=j_nametext.getText();
        int m=name.indexOf(" ");
        if(m!=-1)
        {
            m++;
            name=name.substring(0,1).toUpperCase()+name.substring(1,m)+name.substring(m,m+1).toUpperCase()+name.substring(m+1);
        }
        else
        {
            name=name.substring(0,1).toUpperCase()+name.substring(1);
        }
    }//GEN-LAST:event_j_nametextActionPerformed

    private void j_nametextInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_j_nametextInputMethodTextChanged
        //name=j_nametext.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_j_nametextInputMethodTextChanged

    private void j_nametextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_j_nametextFocusLost
        if(j_nametext.getText().equals(""))
        j_nametext.setText("Enter your name");
    }//GEN-LAST:event_j_nametextFocusLost

    private void j_nametextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_j_nametextFocusGained
        if(j_nametext.getText().equals("Enter your name"))
        j_nametext.setText("");
    }//GEN-LAST:event_j_nametextFocusGained

    private void deg_diplomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deg_diplomaActionPerformed
        degname="Diploma";
    }//GEN-LAST:event_deg_diplomaActionPerformed

    private void deg_hscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deg_hscActionPerformed
        degname="HSC/CBSE";
    }//GEN-LAST:event_deg_hscActionPerformed

    private void languageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageActionPerformed
        lang=language.getText();
    }//GEN-LAST:event_languageActionPerformed

    private void skillsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skillsetActionPerformed
        skills=skillset.getText();
    }//GEN-LAST:event_skillsetActionPerformed

    private void achievementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_achievementActionPerformed
        achieve=achievement.getText();
    }//GEN-LAST:event_achievementActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Experience obj=new Experience(companyname.getText(),workdone.getText(),workdescript.getText());
        exp.add(obj);
        companyname.setText("");
        workdone.setText("");
        workdescript.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void imagepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagepathActionPerformed
        image=imagepath.getText();
    }//GEN-LAST:event_imagepathActionPerformed

    private void checkImagebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkImagebtnActionPerformed
        /*try {
            evt=null;
            imagepathActionPerformed(evt);
            if(isImage(image))
            {
                image_checker=true;
                imageSay.setText("Image path is correct");
            }
            else
            {
                image_checker=false;
                imageSay.setText("Image path is invalid....please try again");
            }// TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(New.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg","jpeg","png","gif");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File selectedfile = file.getSelectedFile();
            image = selectedfile.getAbsolutePath();
            imagepath.setText(image);
            image_checker=true;
        }
        else if(result == JFileChooser.CANCEL_OPTION)
        {}
    }//GEN-LAST:event_checkImagebtnActionPerformed

    private void phonenoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonenoFocusGained
        if(phoneno.getText().equals("Enter your  phone number"))
            phoneno.setText("");
    }//GEN-LAST:event_phonenoFocusGained

    private void phonenoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phonenoFocusLost
        if(phoneno.getText().equals(""))
            phoneno.setText("Enter your  phone number");
    }//GEN-LAST:event_phonenoFocusLost

    private void j_linkedtextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_j_linkedtextFocusGained
        if(j_linkedtext.getText().equals("Enter your LinkedIn iD"))
            j_linkedtext.setText("");
    }//GEN-LAST:event_j_linkedtextFocusGained

    private void j_linkedtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_j_linkedtextFocusLost
        if(j_linkedtext.getText().equals(""))
            j_linkedtext.setText("Enter your LinkedIn iD");     
    }//GEN-LAST:event_j_linkedtextFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            evt=null;
            imagepathActionPerformed(evt);
            if(isImage(image))
            {
                image_checker=true;
                imageSay.setText("Image path is correct");
            }
            else
            {
                image_checker=false;
                imageSay.setText("Image path is invalid....please try again");
            }// TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(New.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    private void achievement_descriptionActionPerformed(java.awt.event.ActionEvent evt) 
    {
        achieve_descript=achievement_description.getText();
    }
    
    public boolean check_submit()
    {
        
        ActionEvent evt = null;
        j_nametextActionPerformed(evt);
        j_emailtextActionPerformed(evt);
        j_jctextActionPerformed(evt);
        j_jcpertextActionPerformed(evt);
        j_schoolpertextActionPerformed(evt);
        j_schooltextActionPerformed(evt);
        j_linkedtextActionPerformed(evt);
        clgnameActionPerformed(evt);
        clgdegActionPerformed(evt);
        cgpaActionPerformed(evt);
        phonenoActionPerformed(evt);
        prodesnameActionPerformed(evt);
        languageActionPerformed(evt);
        skillsetActionPerformed(evt);
        achievementActionPerformed(evt);
        achievement_descriptionActionPerformed(evt);
        check_email();
        imagepathActionPerformed(evt);
        //return true;
        if(!"".equals(name) && !"".equals(email) && !"".equals(phone) && !"".equals(schoolname) && !"".equals(schoolpercent) && !"".equals(jc) && !"".equals(jcpercent) && !"".equals(collegename) && !"".equals(collegedeg) && !"".equals(collegecgpa))
        {
            if(check_phone())
            {}  // return true;
            else
            {
                new Phone();//ALAG POPUP AANA CHAHIYE
                return false;
            }     
        }
        else
        {
            new Popup();
            return false;
        }
        
        CheckNum obj=new CheckNum();
        if (!obj.isNumeric(schoolpercent) && !obj.isNumeric(jcpercent) && !obj.isNumeric(collegecgpa)  )
               {
                    obj.popback();
                    return false;
               }
        else 
            {
                    
            }
                
                return true;
                
                
    }    
    public boolean check_phone()
    {
        //int a=(int) (Integer.parseInt(phone)%pow(10,9));
        long a=(long) (Long.parseLong(phone)/pow(10,9));
        return a>0 && a<10;
    }
    
    public void check_email()
    {
        if(!email.contains("@"))
            email=email+"@gmail.com";
    }
    
    private void prodesnameActionPerformed(java.awt.event.ActionEvent evt){
        descript=prodesname.getText();
    }
    boolean isImage(String image_path) throws MalformedURLException, IOException{
    java.awt.Image image = new ImageIcon(image_path).getImage();
    if(image.getWidth(null) == -1){
         return false;
    }
    else
    {
         return true;
    }
    /*String url1 = image_path;
    BufferedImage img = ImageIO.read(new URL(url1));
    return img != null;*/
}
    
    
    
    
    
    public void submit_cv()
    {
        try{
            
        Document doc=new Document();
        PdfWriter.getInstance(doc,new FileOutputStream(name+".pdf"));
        Font heading = new Font(FontFamily.HELVETICA,26,Font.BOLD);
        Font f1 = new Font(FontFamily.HELVETICA,18,Font.BOLD | Font.UNDERLINE);
        Font f2=new Font(FontFamily.TIMES_ROMAN,16,Font.BOLD);
        Font bold=new Font(FontFamily.TIMES_ROMAN,14,Font.BOLD);
        doc.open();
       
        Paragraph head=new Paragraph(name+"",heading);
        
        head.setAlignment(Paragraph.ALIGN_LEFT);
        doc.add(head);
        doc.add(new Paragraph("Email:"+email+""));
        doc.add(new Paragraph("Phone No:"+phone+""));
        if(!linkid.equals(""))
            doc.add(new Paragraph("LinkedIn-ID:"+linkid+""));
        
        
        if(image_checker)
        {
            Image photo;                             
            photo =Image.getInstance(image);
            photo.setAbsolutePosition(420,720);
            photo.scaleAbsoluteHeight(100);
            photo.scaleAbsoluteWidth(90);
            //photo.setAlignment(Paragraph.ALIGN_RIGHT);
            doc.add(photo);
        }
        else
        {
            
        }
        Chunk linebreak = new Chunk(new DottedLineSeparator());
        doc.add(linebreak);
        
        doc.add(new Paragraph("Education Qualifications"+"",f1));
        doc.add(new Paragraph(schoolname+"",bold));
        doc.add(new Paragraph(schoolpercent+"%"+""));
        //doc.add(Chunk.NEWLINE);
        doc.add(new Paragraph(jc+"",bold));
        //GUI SE BOTTON WALA ISME USE KARNA HAI(IF HSC THEN PRINT HSC+PERCENT)
        if("Diploma".equals(degname))
            doc.add(new Paragraph("Diploma:"+jcpercent+"%"+""));
        else
            doc.add(new Paragraph("Maharastra State Board::"+jcpercent+"%"+""));           
        //doc.add(Chunk.NEWLINE);
        doc.add(new Paragraph(collegename+"",bold));
        doc.add(new Paragraph(collegedeg+""));
        doc.add(new Paragraph("CGPA:"+collegecgpa+""));
        
        
        
        Font f7 = new Font(Font.FontFamily.HELVETICA,18,Font.BOLD );
        //adding projects only if size!=0
        if(!project.isEmpty())
        {
            doc.add(linebreak);
            doc.add(Chunk.NEWLINE);
            doc.add(new Paragraph("Project"+"",f1));
            doc.add(new Paragraph("\n"));
            doc.add(new Paragraph("\n"));

        
        PdfPTable table = new PdfPTable(new float[] { 2,3});
	table.getDefaultCell().setHorizontalAlignment(Element.ALIGN_LEFT);
        table.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
        table.addCell(new Paragraph("Name",f7));
        table.addCell(new Paragraph("Description",f7));
        for(int j=0;j<project.size();j++)
        {
            New_Project obj=new New_Project();
            obj=project.get(j);
            table.addCell(obj.project_name+"");
            table.addCell(new Paragraph(obj.project_descript+""));
            table.addCell(new Paragraph("\n"+""));
            table.addCell(new Paragraph("\n"+""));
        }
        doc.add(table);
        }
        //adding projects
        /*for(int j=0;j<project.size();j++)
        {
            New_Project obj=new New_Project();
            obj=project.get(j);
            doc.add(new Paragraph("Project Name:"+obj.project_name+"",f2));
            doc.add(new Paragraph(obj.project_descript+""));
        }*///end exp proj wala part
        
        
        
        
        
        Font f23 = new Font(Font.FontFamily.HELVETICA,15,Font.BOLD );
        Font f21 = new Font(Font.FontFamily.HELVETICA,10,Font.ITALIC );

        //adding experience if exp!=0
        if(!exp.isEmpty())
        {
            doc.add(linebreak);
            doc.add(Chunk.NEWLINE);
            doc.add(new Paragraph("Experience"+"",f1));
        }
        
        /*PdfPTable table = new PdfPTable(new float[] { 2,3});
	table.getDefaultCell().setHorizontalAlignment(Element.ALIGN_LEFT);
        table.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
        table.addCell(new Paragraph("Company",f7));
        table.addCell(new Paragraph("Job Profile",f7));
        for(int j=0;j<project.size();j++)
        {
            Experience obj=new Experience();
            obj=exp.get(j);
            PdfPCell cell=new PdfPCell();
            cell.setBorder(PdfPCell.NO_BORDER);
            cell.addElement(new Paragraph(obj.company,f23));
            cell.addElement(new Paragraph(obj.work,f21));
            table.addCell(cell);
            //table.addCell("Project Name:"+obj.company+"");          
            table.addCell(new Paragraph(obj.description+""));
        }
        doc.add(table);
        }*/
        
        
        //adding experience
        
        for(int j=0;j<exp.size();j++)
        {
            Experience ob=new Experience();
            ob=exp.get(j);
            doc.add(new Paragraph("Company Name:"+ob.company+"",f2));
            doc.add(new Paragraph(ob.work+"\n"+ob.description+"\n"+""));
        }
    
        
        
        
        
        
        if( !"".equals(lang) || !"".equals(skills) || !"".equals(achieve)  || !"".equals(achieve_descript))
        {
            doc.add(linebreak);
            doc.add(Chunk.NEWLINE);
            doc.add(new Paragraph("Skills & Achievements"+"",f1));           
        }
        if(!"".equals(achieve))
            doc.add(new Paragraph("Achivements:"+achieve+"",bold));
        if(!"".equals(achieve_descript))
        {
            doc.add(new Paragraph(achieve_descript));
            doc.add(Chunk.NEWLINE);
        }
        
        if(!"".equals(lang))
        {
            doc.add(new Paragraph("Languages Known:"+lang+"",bold)); 
            doc.add(Chunk.NEWLINE);
        }
        
        if(!"".equals(skills))
        {
            doc.add(new Paragraph("SkillSet:"+skills+"",bold));
            doc.add(Chunk.NEWLINE);
        }        
        //doc.add(new Paragraph(image+""));
        
        
        //doc.add(new Paragraph("Email:"+email+"")); 
        
        /*doc.add( Chunk.NEWLINE );
        PdfPCell myCell = new PdfPCell(new Paragraph("Hello World") );
        doc.setBorder(Rectangle.BOTTOM);*/
  

        doc.close();
        }
        catch(DocumentException | IOException e){}
    }
    public static void main(String args[])  {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New().setVisible(true);
            }
        });
        /* Set the Nimbus look and feel */
        
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField achievement;
    private javax.swing.JTextArea achievement_description;
    private javax.swing.JTextField cgpa;
    private javax.swing.JButton checkImagebtn;
    private javax.swing.JTextField clgdeg;
    private javax.swing.JTextField clgname;
    private javax.swing.JTextField companyname;
    private javax.swing.JRadioButton deg_diploma;
    private javax.swing.JRadioButton deg_hsc;
    private javax.swing.ButtonGroup degreename;
    private javax.swing.JLabel imageSay;
    private javax.swing.JTextField imagepath;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField j_emailtext;
    private javax.swing.JTextField j_jcpertext;
    private javax.swing.JTextField j_jctext;
    private javax.swing.JTextField j_linkedtext;
    private javax.swing.JLabel j_name;
    private javax.swing.JTextField j_nametext;
    private javax.swing.JTextField j_schoolpertext;
    private javax.swing.JTextField j_schooltext;
    private javax.swing.JButton j_submit;
    private javax.swing.JLabel jl;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl2;
    private javax.swing.JLabel jl3;
    private javax.swing.JLabel jl4;
    private javax.swing.JLabel jl5;
    private javax.swing.JLabel jl6;
    private javax.swing.JLabel jl7;
    private javax.swing.JLabel jl8;
    private javax.swing.JLabel jl9;
    private javax.swing.JTextField language;
    private javax.swing.JButton newprojectBtn;
    private javax.swing.JTextField phoneno;
    private javax.swing.JTextArea prodesname;
    private javax.swing.JTextField proname;
    private javax.swing.JTextField skillset;
    private javax.swing.JTextArea workdescript;
    private javax.swing.JTextField workdone;
    // End of variables declaration//GEN-END:variables

    private New(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
